src/Entity/Route.php
<?php

namespace App\Entity;

use App\Repository\RouteRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: RouteRepository::class)]
class Route
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne]
    private ?Port $depart_port = null;

    #[ORM\ManyToOne]
    private ?Port $arrival_port = null;

    #[ORM\OneToMany(targetEntity: Schedule::class, mappedBy: 'route_id')]
    private Collection $schedules;

    #[ORM\ManyToOne]
    private ?RouteCategory $category_id = null;

    public function __construct()
    {
        $this->schedules = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDepartPort(): ?Port
    {
        return $this->depart_port;
    }

    public function setDepartPort(?Port $depart_port): static
    {
        $this->depart_port = $depart_port;

        return $this;
    }

    public function getArrivalPort(): ?Port
    {
        return $this->arrival_port;
    }

    public function setArrivalPort(?Port $arrival_port): static
    {
        $this->arrival_port = $arrival_port;

        return $this;
    }

    /**
     * @return Collection<int, Schedule>
     */
    public function getSchedules(): Collection
    {
        return $this->schedules;
    }

    public function addSchedule(Schedule $schedule): static
    {
        if (!$this->schedules->contains($schedule)) {
            $this->schedules->add($schedule);
            $schedule->setRouteId($this);
        }

        return $this;
    }

    public function removeSchedule(Schedule $schedule): static
    {
        if ($this->schedules->removeElement($schedule)) {
            // set the owning side to null (unless already changed)
            if ($schedule->getRouteId() === $this) {
                $schedule->setRouteId(null);
            }
        }

        return $this;
    }

    public function getCategoryId(): ?RouteCategory
    {
        return $this->category_id;
    }

    public function setCategoryId(?RouteCategory $category_id): static
    {
        $this->category_id = $category_id;

        return $this;
    }
}

src/Entity/Schedule.php
<?php

namespace App\Entity;

use App\Repository\ScheduleRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ScheduleRepository::class)]
class Schedule
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'schedules')]
    private ?Route $route_id = null;

    #[ORM\Column(type: Types::DATE_IMMUTABLE)]
    private ?\DateTimeImmutable $start_date = null;

    #[ORM\Column(type: Types::DATE_IMMUTABLE)]
    private ?\DateTimeImmutable $end_date = null;

    #[ORM\Column]
    private ?int $start_hour = null;

    #[ORM\Column]
    private ?int $start_minute = null;

    #[ORM\Column]
    private ?int $end_hour = null;

    #[ORM\Column]
    private ?int $end_minute = null;

    #[ORM\OneToMany(targetEntity: Price::class, mappedBy: 'schedule_id')]
    private Collection $prices;

    #[ORM\ManyToOne]
    private ?Vehicle $vehicle_id = null;

    public function __construct()
    {
        $this->prices = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getRouteId(): ?Route
    {
        return $this->route_id;
    }

    public function setRouteId(?Route $route_id): static
    {
        $this->route_id = $route_id;

        return $this;
    }

    public function getStartDate(): ?\DateTimeImmutable
    {
        return $this->start_date;
    }

    public function setStartDate(\DateTimeImmutable $start_date): static
    {
        $this->start_date = $start_date;

        return $this;
    }

    public function getEndDate(): ?\DateTimeImmutable
    {
        return $this->end_date;
    }

    public function setEndDate(\DateTimeImmutable $end_date): static
    {
        $this->end_date = $end_date;

        return $this;
    }

    public function getStartHour(): ?int
    {
        return $this->start_hour;
    }

    public function setStartHour(int $start_hour): static
    {
        $this->start_hour = $start_hour;

        return $this;
    }

    public function getStartMinute(): ?int
    {
        return $this->start_minute;
    }

    public function setStartMinute(int $start_minute): static
    {
        $this->start_minute = $start_minute;

        return $this;
    }

    public function getEndHour(): ?int
    {
        return $this->end_hour;
    }

    public function setEndHour(int $end_hour): static
    {
        $this->end_hour = $end_hour;

        return $this;
    }

    public function getEndMinute(): ?int
    {
        return $this->end_minute;
    }

    public function setEndMinute(int $end_minute): static
    {
        $this->end_minute = $end_minute;

        return $this;
    }

    /**
     * @return Collection<int, Price>
     */
    public function getPrices(): Collection
    {
        return $this->prices;
    }

    public function addPrice(Price $price): static
    {
        if (!$this->prices->contains($price)) {
            $this->prices->add($price);
            $price->setScheduleId($this);
        }

        return $this;
    }

    public function removePrice(Price $price): static
    {
        if ($this->prices->removeElement($price)) {
            // set the owning side to null (unless already changed)
            if ($price->getScheduleId() === $this) {
                $price->setScheduleId(null);
            }
        }

        return $this;
    }

    public function getVehicleId(): ?Vehicle
    {
        return $this->vehicle_id;
    }

    public function setVehicleId(?Vehicle $vehicle_id): static
    {
        $this->vehicle_id = $vehicle_id;

        return $this;
    }
}

src/Form/ScheduleType.php
<?php

namespace App\Form;

use App\Entity\Route;
use App\Entity\Schedule;
use App\Entity\Vehicle;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\FormEvent;
use Symfony\Component\Form\FormEvents;


class ScheduleType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('route_id', EntityType::class, [
                'class' => Route::class,
                'choice_label' => function (Route $route) {
                    return $route->getDepartPort()->getName() . ' - ' . $route->getArrivalPort()->getName();
                },
            ])
        
            ->add('start_date', DateType::class, [
                'data' => new \DateTime('8888-01-01'),
                'format' => 'yyyy-MM-dd',
                'attr' => [
                    'style' => 'pointer-events: none;'
                ]
            ])
            ->add('end_date', DateType::class, [
                'data' => new \DateTime('8888-12-31'),
                'format' => 'yyyy-MM-dd',
                'attr' => [
                    'style' => 'pointer-events: none;'
                ]
            ])
            ->add('start_hour')
            ->add('start_minute')
            ->add('end_hour')
            ->add('end_minute')
            ->add('vehicle_id', EntityType::class, [
                'class' => Vehicle::class,
                'choice_label' => 'id',
            ]);

        // フォームイベントリスナーを追加
        $builder->addEventListener(FormEvents::PRE_SUBMIT, function (FormEvent $event) {
            $data = $event->getData(); // フォームのデータを取得

            // start_dateとend_dateの年を8888に設定
            foreach (['start_date', 'end_date'] as $field) {
                if (isset($data[$field])) {
                    $date = new \DateTime($data[$field]);
                    $date->setDate(8888, $date->format('m'), $date->format('d'));
                    $data[$field] = $date->format('Y-m-d');
                }
            }

            $event->setData($data); // 変更したデータをフォームに設定
        });

    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Schedule::class,
        ]);
    }
}

src/Controller/ScheduleController.php
<?php

namespace App\Controller;

use App\Entity\Schedule;
use App\Form\ScheduleType;
use App\Repository\ScheduleRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/edit/schedule')]
class ScheduleController extends AbstractController
{
    #[Route('/', name: 'app_schedule_index', methods: ['GET'])]
    public function index(ScheduleRepository $scheduleRepository): Response
    {
        return $this->render('schedule/index.html.twig', [
            'schedules' => $scheduleRepository->findAllDesc(),
        ]);
    }

    #[Route('/new', name: 'app_schedule_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $schedule = new Schedule();
        $form = $this->createForm(ScheduleType::class, $schedule);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            // 重複チェック
            $scheduleRepository = $entityManager->getRepository(Schedule::class);
            $existSchedule = $scheduleRepository->findOneByDateTime(
                $schedule->getRouteId(),
                $schedule->getStartDate(),
                $schedule->getEndDate(),
                $schedule->getStartHour(),
                $schedule->getStartMinute(),
                $schedule->getEndHour(),
                $schedule->getEndMinute()
            );

            if ($existSchedule) {
                $this->addFlash('danger', '既に同じスケジュールが登録されています');
                return $this->redirectToRoute('app_schedule_new', [], Response::HTTP_SEE_OTHER);
            }

            $entityManager->persist($schedule);
            $entityManager->flush();

            return $this->redirectToRoute('app_schedule_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('schedule/new.html.twig', [
            'schedule' => $schedule,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_schedule_show', methods: ['GET'])]
    public function show(Schedule $schedule): Response
    {
        return $this->render('schedule/show.html.twig', [
            'schedule' => $schedule,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_schedule_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Schedule $schedule, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(ScheduleType::class, $schedule);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_schedule_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('schedule/edit.html.twig', [
            'schedule' => $schedule,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_schedule_delete', methods: ['POST'])]
    public function delete(Request $request, Schedule $schedule, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$schedule->getId(), $request->request->get('_token'))) {
            $entityManager->remove($schedule);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_schedule_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/schedule/_delete_form.html.twig
<form method="post" action="{{ path('app_schedule_delete', {'id': schedule.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ schedule.id) }}">
    <button class="btn btn-outline-danger">削除</button>
</form>

templates/schedule/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-primary mb-2">{{ button_label|default('保存') }}</button>
{{ form_end(form) }}

templates/schedule/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Schedule{% endblock %}

{% block body %}
    <h1>Edit Schedule</h1>

    {{ include('schedule/_form.html.twig', {'button_label': '更新'}) }}

    <a href="{{ path('app_schedule_index') }}" class="btn btn-outline-secondary mb-2">一覧</a>

    {{ include('schedule/_delete_form.html.twig') }}
{% endblock %}

templates/schedule/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Schedule index{% endblock %}

{% block body %}
    <h1>Schedule index</h1>

    <a href="{{ path('app_schedule_new') }}" class="btn btn-primary mb-2">新規作成</a>
    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Route</th>
                <th>Start_date</th>
                <th>End_date</th>
                <th>Start_hour</th>
                <th>End_hour</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for schedule in schedules %}
            <tr>
                <td>{{ schedule.id }}</td>
                <td>{{ schedule.routeId.departPort.name }} - {{ schedule.routeId.arrivalPort.name }}</td>
                <td>{{ schedule.startDate ? schedule.startDate|date('m-d') : '' }}</td>
                <td>{{ schedule.endDate ? schedule.endDate|date('m-d') : '' }}</td>
                <td>{{ schedule.startHour }}:{{ schedule.startMinute }}</td>
                <td>{{ schedule.endHour }}:{{ schedule.endMinute }}</td>
                <td>
                    <a href="{{ path('app_schedule_show', {'id': schedule.id}) }}" class="btn btn-outline-secondary mb-2">表示</a>
                    <a href="{{ path('app_schedule_edit', {'id': schedule.id}) }}" class="btn btn-outline-secondary mb-2">編集</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="8">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock %}

templates/schedule/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Schedule{% endblock %}

{% block body %}
    <h1>新しい運行スケジュールを作成する</h1>

    {{ include('schedule/_form.html.twig') }}

    <a href="{{ path('app_schedule_index') }}" class="btn btn-outline-secondary mb-2">一覧</a>
{% endblock %}

templates/schedule/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Schedule{% endblock %}

{% block body %}
    <h1>Schedule</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ schedule.id }}</td>
            </tr>
            <tr>
                <th>Start_date</th>
                <td>{{ schedule.startDate ? schedule.startDate|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>End_date</th>
                <td>{{ schedule.endDate ? schedule.endDate|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Start_hour</th>
                <td>{{ schedule.startHour }}</td>
            </tr>
            <tr>
                <th>Start_minute</th>
                <td>{{ schedule.startMinute }}</td>
            </tr>
            <tr>
                <th>End_hour</th>
                <td>{{ schedule.endHour }}</td>
            </tr>
            <tr>
                <th>End_minute</th>
                <td>{{ schedule.endMinute }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_schedule_index') }}" class="btn btn-outline-secondary mb-2">一覧</a>

    <a href="{{ path('app_schedule_edit', {'id': schedule.id}) }}" class="btn btn-outline-secondary mb-2">編集</a>

    {{ include('schedule/_delete_form.html.twig') }}
{% endblock %}